### ISSUE TITLE
Missing Example Project

### ISSUE THREAD

**Issue by oninoni** [Meachamp/gm_8bit#3]
The Readme mentions a "voice-relay" repository, that shows an example of using the data.
I'm having problem with interpreting it and would love to see that repository.

Im currently trying to do voice recognition using this

**Comment by Meachamp** [comment]
It exists but the code needs to be looked at before I'd be comfortable making it public. I know it's been a few months since the inception of the project, but it hasn't been high on my priority list. I can possibly (hopefully) get something out for you after I finish testing 64-bit linux support.

**Comment by oninoni** [comment]
I assumed it was set to private.
I can help you testing 64bit support. I've gotten some experience of compiling to 64bit for gmod. I'll give it a try.

**Comment by Meachamp** [comment]
It's about done, just finishing up some changes this morning. If you want to test it before I merge, checkout 64-bit branch. You'll need the 64 bit branch garrysmod_common as well.

**Comment by oninoni** [comment]
Could you maybe point me at some libraries you can use for the processing of the voice data as a javascript project? (Im assuming the discord script is js aswell?)

**Comment by Meachamp** [comment]
It can be done with any standard opus implementation and some code to properly extract the frames from the steam voice packet that gm_8bit relays. If you look in the `templates` folder you'll see a binary template that describes the reverse engineered steam voice packet structure.

**Comment by oninoni** [comment]
Any progress? Still very confused on the way to handle the packages. An example would really help.
Even if its not perfect

**Comment by Meachamp** [comment]
Sorry for the wait. I haven't had a chance to attack this one yet, but it's next up on the to-do list. I'll let you know more once things start happening.

**Comment by oninoni** [comment]
Any progress? I can't seem to understand the format. If I understand this right they should be 16 bit PCM format but sometimes it's not an even number of bytes being transmitted. An example of how to convert into a standard nodejs sound packet file would really be nice. Even if it's not perfect. I just want to start testing passing the data to other libraries

**Comment by Mattzi** [comment]
So, im working together with @oninoni to get this working.

We got everything worked out with the steam voice packets and extracting the frames from there.
Now we got everything in the steam voice packet + a buffer with our voice data.

To try this whole thing we want to pipe those voice buffers to discord, but just cant get this to work.
Are you able to give us this last bit of code on how to pipe those buffers to our discord.js voice connection?

**Comment by Meachamp** [comment]
I'm really not happy about the code quality, but I still haven't had time to deal with it. For now, I've just made voice-relay public here: https://github.com/Meachamp/voice-relay. It's designed to be run in a docker container, and currently exits after a period of time to deal with a longstanding bug in discord.js, where a voice connection stops working after some time. See issue https://github.com/discordjs/discord.js/issues/4021

It uses a modified version of  `@discordjs/opus` for frame size adjustments and a forked `audio-mixer` for CPU usage fixes. There's a lot that needs to be fixed with it, but hopefully this is at least helpful for now. If you do end up making improvements to the code, PRs are always appreciated.
